version: "3"
services:
  website:
    build:
      context: docker/production
    image: quay.io/jkadlcik/log-detective
    hostname: log-detective
    stdin_open: true
    tty: true
    ports:
      - 8080:80
    volumes:
      - persistent:/persistent:z

volumes:
  persistent:
