version: "3"
services:
  backend:
    build:
      context: docker/backend
    hostname: backend
    working_dir: /opt/log-detective-website/backend
    command: "uvicorn api:app --host 0.0.0.0 --port 5020"
    stdin_open: true
    tty: true
    ports:
      - 5020:5020
    volumes:
      - .:/opt/log-detective-website:z
      - persistent:/persistent
    environment:
      - ENV=devel
      - FEEDBACK_DIR=/persistent/results
      - PYTHONPATH=/opt/log-detective-website
  # The frontend container is only a quality of life for development.
  # For production, we will simply compile the ClojureScript into JavaScript
  # and deploy it.
  frontend:
    build:
      context: docker/frontend
    hostname: frontend
    working_dir: /opt/log-detective-website/frontend
    command: "npx shadow-cljs watch app"
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 9630:9630
      - 3333:3333
    volumes:
      - .:/opt/log-detective-website:z
    environment:
      - ENV=devel
      - FEEDBACK_DIR=/persistent/results

volumes:
  persistent:
